<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<WasmAppProjectName>DotNetIsolator.WasmApp</WasmAppProjectName>
		<WasmAppRuntimeIdentifier>wasi-wasm</WasmAppRuntimeIdentifier>
		<BundledFilesDir>IsolatedRuntimeHost\</BundledFilesDir>
		<NoWarn>$(NoWarn);NU5100</NoWarn> <!-- We're bundling some .dlls as content, so don't warn about them not being in lib -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" Version="3.1.6" />
		<PackageReference Include="Wasmtime" Version="44.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="build\DotNetIsolator.props" PackagePath="build" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\DotNetIsolator.Guest\GuestToHostCall.cs" />
		<Compile Include="..\DotNetIsolator.Guest\MessagePackCompatibility.cs" />
		<Compile Include="..\DotNetIsolator.Guest\ObjectGraphObjectSerializer.cs" />
		<Compile Include="..\DotNetIsolator.Guest\ObjectGraphPrimitiveCollections.cs" />
		<Compile Include="..\DotNetIsolator.Guest\ObjectGraphPrimitives.cs" />
		<Compile Include="..\DotNetIsolator.Guest\ObjectGraphSerializer.cs" />
		<Compile Include="..\DotNetIsolator.Guest\ObjectGraphTypes.cs" />
		<Compile Include="..\DotNetIsolator.Guest\PrimitiveScalarCodec.cs" />
		<Compile Include="..\DotNetIsolator.Guest\generated\MessagePackGenerated.cs" />
	</ItemGroup>

	<!-- Reference the WasmApp project in such a way that we acquire its .wasm and WebAssembly BCL (.dll) files, but not its primary assembly -->
	<ItemGroup>		
		<ProjectReference Include="..\DotNetIsolator.WasmApp\DotNetIsolator.WasmApp.csproj">
		  <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<Content Include="..\$(WasmAppProjectName)\bin\$(Configuration)\$(TargetFramework)\$(WasmAppRuntimeIdentifier)\AppBundle\$(WasmAppProjectName).wasm">
			<Visible>false</Visible>
			<Link>$(BundledFilesDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>true</Pack>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<PackagePath>contentFiles\any\any\$(BundledFilesDir)%(Filename)%(Extension)</PackagePath>
		</Content>
	</ItemGroup>

</Project>
